language: java
dist: trusty
jdk: openjdk8
sudo: false
install: true
jobs:
  include:
  - stage: head
    script: mvn -B verify
deploy:
  provider: pages
  skip_cleanup: true # to upload artifacts created during the build
  github-token: $GITHUB_TOKEN  # See in the settings of repo
  local-dir: "releng/publish/target"
  public_repo: "mypsycho/modit-updatesite"
  on:
    branch: master